data:extend({
    {
        name = 'umr_item_group',
        type = 'item-group',
        icon = '__ultimateCore__/graphics/umr_group.png',
        icon_size = 128,
        inventory_order = "z",
        order = "e",
    },
    {
        name = 'umr_item_subgroup_a',
        type = 'item-subgroup',
        group = 'umr_item_group',
        order = 'a',
    },
    {
        name = 'umr_item_subgroup_b',
        type = 'item-subgroup',
        group = 'umr_item_group',
        order = 'b',
    },
    {
        name = 'umr_item_subgroup_c',
        type = 'item-subgroup',
        group = 'umr_item_group',
        order = 'c',
    },
    {
        name = 'umr_item_subgroup_d',
        type = 'item-subgroup',
        group = 'umr_item_group',
        order = 'd',
    },
    {
        name = 'umr_item_subgroup_e',
        type = 'item-subgroup',
        group = 'umr_item_group',
        order = 'e',
    },
    {
        name = 'umr_item_subgroup_f',
        type = 'item-subgroup',
        group = 'umr_item_group',
        order = 'f',
    },
    {
        name = 'umr_item_subgroup_g',
        type = 'item-subgroup',
        group = 'umr_item_group',
        order = 'g',
    },
    {
        name = 'umr_item_subgroup_h',
        type = 'item-subgroup',
        group = 'umr_item_group',
        order = 'h',
    },
    {
        name = 'umr_item_subgroup_i',
        type = 'item-subgroup',
        group = 'umr_item_group',
        order = 'i',
    },
    {
        name = 'umr_item_subgroup_j',
        type = 'item-subgroup',
        group = 'umr_item_group',
        order = 'j',
    },
    {
        name = 'umr_item_subgroup_k',
        type = 'item-subgroup',
        group = 'umr_item_group',
        order = 'k',
    },
    {
        name = 'umr_item_subgroup_l',
        type = 'item-subgroup',
        group = 'umr_item_group',
        order = 'l',
    },
    {
        name = 'umr_item_subgroup_m',
        type = 'item-subgroup',
        group = 'umr_item_group',
        order = 'm',
    },
    {
        name = 'umr_item_subgroup_n',
        type = 'item-subgroup',
        group = 'umr_item_group',
        order = 'n',
    },
    {
        name = 'umr_item_subgroup_o',
        type = 'item-subgroup',
        group = 'umr_item_group',
        order = 'o',
    },
    {
        name = 'umr_item_subgroup_p',
        type = 'item-subgroup',
        group = 'umr_item_group',
        order = 'p',
    },
    {
        name = 'umr_item_subgroup_q',
        type = 'item-subgroup',
        group = 'umr_item_group',
        order = 'q',
    },
    {
        name = 'umr_item_subgroup_r',
        type = 'item-subgroup',
        group = 'umr_item_group',
        order = 'r',
    },
    {
        name = 'umr_item_subgroup_s',
        type = 'item-subgroup',
        group = 'umr_item_group',
        order = 's',
    },
    {
        name = 'umr_item_subgroup_t',
        type = 'item-subgroup',
        group = 'umr_item_group',
        order = 't',
    },
})
